DEBUG = True

SQLALCHEMY_DATABASE_URI = 'postgresql://python_user:1DvaTri!@127.0.0.1/IcaptionDB'
SQLALCHEMY_TRACK_MODIFICATIONS = False
DATABASE_CONNECT_OPTIONS = {}

THREADS_PER_PAGE = 2

CSRF_ENABLED = True

CSRF_SESSION_KEY = "secret"

SECRET_KEY = "secret"
