name: icaption
channels:
  - conda-forge
dependencies:
  - python=3.5
  - flask
  - flask-sqlalchemy
  - flask-httpauth
  - pylint
  - sqlalchemy
  - passlib
  - itsdangerous
  - flask-script
  - flask-migrate
  - psycopg2